name: Crypto Signal Bot

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  signal-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the bot
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          CP_KEY: ${{ secrets.CP_KEY }}
          PAIR: BTC/USDT,ETH/USDT,ADA/USDT,SHIB/USDT,XRP/USDT,DOGE/USDT
          TF: 1h
        run: python bot.py
